name: FarmersCut
favicon: null
layout_spectrum: 0.2936500208452344
typography_spectrum: 0.26175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090a04'
    - '#746a5d'
    - '#c6c1bb'
    - '#842290'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.2564862121362239
purpose: []
