title: Local Farmers Community
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6738351
  brandStrength: 1
  lightness: 0.5
  brandColors:
    - '#ffffff'
    - '#090a04'
    - '#746a5d'
    - '#c6c1bb'
    - '#842290'
  rhythmicContrast: 0.797491
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: FarmersCut
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3566308
layout_spectrum: 0.5645161
